version: '3.9'

services:
  grafana:
    image: grafana/grafana:11.5.2
    hostname: grafana
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: "marcusolsson-csv-datasource,yesoreyeram-infinity-datasource"
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_LOG_LEVEL: info
    volumes:
      #- ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./provisioning/:/etc/grafana/provisioning/
    networks:
      - grafana

networks:
  grafana:
    name: grafana
    driver: bridge