- name: Update apt cache
  apt:
    update_cache: true

- name: Install git
  apt:
    name: git
    state: present

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Download Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Enable and start Docker
  service:
    name: docker
    state: started
    enabled: true