- name: Setup grafana
  hosts: grafana
  become: true
  vars:
    repo_url: https://github.com/Aryido/auction
    repo_dest: /home/auction
    compose_folder: /home/auction/grafana
  roles:
    - setup_env
    - deploy_grafana